import { DEFAULT_STYLE, type CaptionStyle } from './captionStyle';

export interface StylePreset {
  name: string;
  style: CaptionStyle;
}

function p(name: string, o: Partial<CaptionStyle>): StylePreset {
  return { name, style: { ...DEFAULT_STYLE, ...o } };
}

export const STYLE_PRESETS: StylePreset[] = [
  // ── Named styles ──────────────────────────────────────────────────────────
  p('mosy',           { fontFamily: 'Nunito',           fontSize: 12, textColor: '#FFFFFF', outlineColor: '#1a1a1a', outlineWidth: 1,   animation: 'fade' }),
  p('clean bold',     { fontFamily: 'Montserrat',       fontSize: 14, bold: true,  letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2 }),
  p('swirl',          { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#f472b6', outlineColor: '#7c3aed', outlineWidth: 1,   animation: 'word-pop' }),
  p('sway',           { fontFamily: 'Raleway',          fontSize: 12, italic: true, textColor: '#bae6fd', outlineColor: '#1e3a5f', outlineWidth: 1, animation: 'fade' }),
  p('lunar',          { fontFamily: 'Inter',            fontSize: 12, textColor: '#e2e8f0', outlineColor: '#0f172a', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#0f172a', backgroundOpacity: 0.7 }),
  p('u up?',          { fontFamily: 'Poppins',          fontSize: 14, bold: true,  textColor: '#f472b6', outlineColor: '#000000', outlineWidth: 2,   animation: 'word-pop' }),
  p('keynote',        { fontFamily: 'Montserrat',       fontSize: 13, bold: true,  textColor: '#FFFFFF', outlineColor: '#1e3a8a', outlineWidth: 0,   hasBackground: true, backgroundColor: '#1e3a8a', backgroundOpacity: 0.9 }),
  p('viral',          { fontFamily: 'Bebas Neue',       fontSize: 18, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('blue bubble',    { fontFamily: 'Nunito',           fontSize: 12, bold: true,  textColor: '#FFFFFF', outlineColor: '#2563eb', outlineWidth: 0,   hasBackground: true, backgroundColor: '#2563eb', backgroundOpacity: 0.9, animation: 'fade' }),
  p('Y2K Diva',       { fontFamily: 'Poppins',          fontSize: 13, bold: true,  textColor: '#f472b6', outlineColor: '#7c3aed', outlineWidth: 2,   animation: 'word-pop', letterSpacing: 1 }),
  p('kitty 2',        { fontFamily: 'Nunito',           fontSize: 12, textColor: '#ec4899', outlineColor: '#fff0f8', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#fce7f3', backgroundOpacity: 0.85 }),
  p('yellow press',   { fontFamily: 'Oswald',           fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('bolt',           { fontFamily: 'Bebas Neue',       fontSize: 18, letterCase: 'uppercase', textColor: '#facc15', outlineColor: '#000000', outlineWidth: 3.5, animation: 'impact' }),
  p('ignite',         { fontFamily: 'Montserrat',       fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#f97316', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('header',         { fontFamily: 'Roboto',           fontSize: 14, bold: true,  textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2,   positionY: 10 }),
  p('bold care',      { fontFamily: 'Poppins',          fontSize: 13, bold: true,  textColor: '#fb7185', outlineColor: '#000000', outlineWidth: 1.5, animation: 'fade' }),
  p('power',          { fontFamily: 'Bebas Neue',       fontSize: 18, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('rouge',          { fontFamily: 'Playfair Display', fontSize: 13, italic: true, textColor: '#be123c', outlineColor: '#1c0a0a', outlineWidth: 1,   animation: 'fade' }),
  p('energetic',      { fontFamily: 'Barlow Condensed', fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('circuit',        { fontFamily: 'Inter',            fontSize: 12, textColor: '#22d3ee', outlineColor: '#000000', outlineWidth: 1,   hasBackground: true, backgroundColor: '#0c1a2e', backgroundOpacity: 0.9, animation: 'fade' }),
  p('silent night',   { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#e0e7ff', outlineColor: '#1e1b4b', outlineWidth: 1,   hasBackground: true, backgroundColor: '#1e1b4b', backgroundOpacity: 0.85, animation: 'fade' }),
  p('december',       { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#fefce8', outlineColor: '#1e3a5f', outlineWidth: 0,   hasBackground: true, backgroundColor: '#1e3a5f', backgroundOpacity: 0.9, animation: 'fade' }),
  p('kitty',          { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#f472b6', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('candy bar',      { fontFamily: 'Poppins',          fontSize: 13, bold: true,  textColor: '#FFFFFF', outlineColor: '#be123c', outlineWidth: 0,   hasBackground: true, backgroundColor: '#e11d48', backgroundOpacity: 0.9, animation: 'word-pop' }),
  p('dream sparkle',  { fontFamily: 'Caveat',           fontSize: 14, textColor: '#c4b5fd', outlineColor: '#1e0a3c', outlineWidth: 1,   animation: 'word-pop' }),
  p('sweet monster',  { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#14b8a6', outlineColor: '#000000', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#fce7f3', backgroundOpacity: 0.85, animation: 'word-pop' }),
  p('pastel',         { fontFamily: 'Nunito',           fontSize: 12, textColor: '#f9a8d4', outlineColor: '#1c1917', outlineWidth: 1,   hasBackground: true, backgroundColor: '#fff1f2', backgroundOpacity: 0.8, animation: 'fade' }),
  p('monster',        { fontFamily: 'Bebas Neue',       fontSize: 18, letterCase: 'uppercase', textColor: '#84cc16', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('cartoony',       { fontFamily: 'Pacifico',         fontSize: 14, textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 3.5, animation: 'word-pop' }),
  p('choco treat',    { fontFamily: 'Nunito',           fontSize: 12, textColor: '#fef3c7', outlineColor: '#451a03', outlineWidth: 1,   hasBackground: true, backgroundColor: '#78350f', backgroundOpacity: 0.9, animation: 'fade' }),
  p('disconnected',   { fontFamily: 'Inter',            fontSize: 12, textColor: '#FFFFFF', outlineColor: '#6b7280', outlineWidth: 0.5, letterSpacing: 2 }),
  p('dollhouse',      { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#f472b6', outlineColor: '#7c3aed', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fdf2f8', backgroundOpacity: 0.85, animation: 'fade' }),
  p('valentine',      { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#f43f5e', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('bubblegum',      { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#f472b6', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('comic hero',     { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 0, hasBackground: true, backgroundColor: '#dc2626', backgroundOpacity: 1, animation: 'impact' }),
  p('spookspire',     { fontFamily: 'Oswald',           fontSize: 14, textColor: '#f97316', outlineColor: '#000000', outlineWidth: 2,   hasBackground: true, backgroundColor: '#0c0a09', backgroundOpacity: 0.85, animation: 'fade' }),
  p('skyglen',        { fontFamily: 'Raleway',          fontSize: 12, textColor: '#FFFFFF', outlineColor: '#0369a1', outlineWidth: 1,   hasBackground: true, backgroundColor: '#0ea5e9', backgroundOpacity: 0.25, animation: 'fade' }),
  p('timeless',       { fontFamily: 'Playfair Display', fontSize: 13, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('glow',           { fontFamily: 'Inter',            fontSize: 12, textColor: '#FFFFFF', outlineColor: '#06b6d4', outlineWidth: 2.5, animation: 'fade' }),
  p('u-bank',         { fontFamily: 'Roboto',           fontSize: 11, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.65 }),
  p('ghost',          { fontFamily: 'Raleway',          fontSize: 12, italic: true, textColor: '#f1f5f9', outlineColor: '#334155', outlineWidth: 0.5, animation: 'fade' }),
  p('academic',       { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#1c1917', outlineColor: '#FFFFFF', outlineWidth: 0.5 }),
  p('woods',          { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#d9f99d', outlineColor: '#1a2e05', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#14532d', backgroundOpacity: 0.85, animation: 'fade' }),
  p('paperback',      { fontFamily: 'Playfair Display', fontSize: 11, italic: true, textColor: '#44403c', outlineColor: '#fef3c7', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fef3c7', backgroundOpacity: 0.9 }),
  p('sunshine',       { fontFamily: 'Poppins',          fontSize: 14, bold: true,  textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 2,   animation: 'fade' }),
  p('youtuber',       { fontFamily: 'Montserrat',       fontSize: 14, bold: true,  letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('valentines',     { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#e11d48', outlineColor: '#fce7f3', outlineWidth: 1,   animation: 'fade' }),
  p('apple',          { fontFamily: 'Inter',            fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.6 }),
  p('showgirl',       { fontFamily: 'Pacifico',         fontSize: 14, textColor: '#fbbf24', outlineColor: '#1c0a0a', outlineWidth: 1.5, animation: 'word-pop' }),
  p('memoir',         { fontFamily: 'Merriweather',     fontSize: 11, italic: true, textColor: '#78716c', outlineColor: '#fef3c7', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fef9ee', backgroundOpacity: 0.9, animation: 'fade' }),
  p('electra',        { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#60a5fa', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('blush',          { fontFamily: 'Nunito',           fontSize: 12, textColor: '#fb7185', outlineColor: '#FFFFFF', outlineWidth: 1.5, animation: 'fade' }),
  p('power sweet',    { fontFamily: 'Poppins',          fontSize: 14, bold: true,  textColor: '#f472b6', outlineColor: '#000000', outlineWidth: 2,   animation: 'impact' }),
  p('spring cottage', { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#4ade80', outlineColor: '#052e16', outlineWidth: 1,   hasBackground: true, backgroundColor: '#f0fdf4', backgroundOpacity: 0.8, animation: 'fade' }),
  p('glare',          { fontFamily: 'Inter',            fontSize: 13, bold: true,  textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 3,   letterSpacing: 1 }),
  p('playful easter', { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#c084fc', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('creamy',         { fontFamily: 'Nunito',           fontSize: 12, textColor: '#fef3c7', outlineColor: '#78350f', outlineWidth: 1 }),
  p('marina',         { fontFamily: 'Raleway',          fontSize: 12, textColor: '#38bdf8', outlineColor: '#0c4a6e', outlineWidth: 1.5, animation: 'fade' }),
  p('neon',           { fontFamily: 'Bebas Neue',       fontSize: 16, textColor: '#a3e635', outlineColor: '#000000', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#0a0a0a', backgroundOpacity: 0.85, animation: 'impact' }),
  p('grapefruit',     { fontFamily: 'Poppins',          fontSize: 13, textColor: '#fb923c', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('pop',            { fontFamily: 'Poppins',          fontSize: 14, bold: true,  textColor: '#f472b6', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('anemone',        { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#a78bfa', outlineColor: '#FFFFFF', outlineWidth: 1.5, animation: 'fade' }),
  p('gelato',         { fontFamily: 'Nunito',           fontSize: 12, textColor: '#f9a8d4', outlineColor: '#fde68a', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#fdf2f8', backgroundOpacity: 0.8, animation: 'word-pop' }),
  p('mario',          { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#dc2626', outlineWidth: 3,   animation: 'impact' }),
  p('vanilla',        { fontFamily: 'Raleway',          fontSize: 12, textColor: '#fef3c7', outlineColor: '#78716c', outlineWidth: 1 }),
  p('alternates',     { fontFamily: 'Montserrat',       fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5, highlightColor: '#FFEB3B', animation: 'karaoke' }),
  p('human',          { fontFamily: 'Lato',             fontSize: 12, textColor: '#FFFFFF', outlineColor: '#1c1917', outlineWidth: 1.5 }),
  p('classy',         { fontFamily: 'Playfair Display', fontSize: 13, bold: true,  textColor: '#fbbf24', outlineColor: '#1c1917', outlineWidth: 1,   animation: 'fade' }),
  p('dusk',           { fontFamily: 'Raleway',          fontSize: 12, textColor: '#e879f9', outlineColor: '#1e1b4b', outlineWidth: 1.5, animation: 'fade' }),
  p('minimal',        { fontFamily: 'Inter',            fontSize: 11, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 0.5 }),
  p('notepad',        { fontFamily: 'Caveat',           fontSize: 13, textColor: '#1c1917', outlineColor: '#fef9c3', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fef9c3', backgroundOpacity: 0.95 }),
  p('whisper',        { fontFamily: 'Raleway',          fontSize: 11, italic: true, textColor: '#d1d5db', outlineColor: '#374151', outlineWidth: 0.5, animation: 'fade' }),
  p('cloud',          { fontFamily: 'Nunito',           fontSize: 12, textColor: '#FFFFFF', outlineColor: '#94a3b8', outlineWidth: 1.5, animation: 'fade' }),
  p('grace',          { fontFamily: 'Playfair Display', fontSize: 13, italic: true, textColor: '#FFFFFF', outlineColor: '#1c1917', outlineWidth: 1,   animation: 'fade' }),
  p('piano',          { fontFamily: 'Merriweather',     fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('old school',     { fontFamily: 'Oswald',           fontSize: 13, textColor: '#fbbf24', outlineColor: '#1c1917', outlineWidth: 1.5, animation: 'fade' }),
  p('cupcake',        { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#f9a8d4', outlineColor: '#fef3c7', outlineWidth: 2,   hasBackground: true, backgroundColor: '#fff0f8', backgroundOpacity: 0.7, animation: 'word-pop' }),
  p('fancy',          { fontFamily: 'Playfair Display', fontSize: 13, bold: true,  italic: true, textColor: '#fbbf24', outlineColor: '#1c1917', outlineWidth: 1.5 }),
  p('terminal',       { fontFamily: 'Source Sans 3',    fontSize: 11, textColor: '#4ade80', outlineColor: '#000000', outlineWidth: 0,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.95, letterSpacing: 1 }),
  p('typewriter',     { fontFamily: 'Source Sans 3',    fontSize: 11, textColor: '#292524', outlineColor: '#fef9ee', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fef9ee', backgroundOpacity: 0.9, letterSpacing: 0.5 }),
  p('box',            { fontFamily: 'Inter',            fontSize: 12, bold: true,  textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 0,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.75 }),
  p('telegraph',      { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#292524', outlineColor: '#e7e5e4', outlineWidth: 0,   hasBackground: true, backgroundColor: '#e7e5e4', backgroundOpacity: 0.85 }),
  p('retro',          { fontFamily: 'Oswald',           fontSize: 13, textColor: '#fb923c', outlineColor: '#1c1917', outlineWidth: 1.5, animation: 'fade' }),
  p('maze',           { fontFamily: 'Barlow Condensed', fontSize: 13, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5, letterSpacing: 1 }),
  p('soft glow',      { fontFamily: 'Nunito',           fontSize: 12, textColor: '#fce7f3', outlineColor: '#ec4899', outlineWidth: 2.5, animation: 'fade' }),
  p('modern serif',   { fontFamily: 'Playfair Display', fontSize: 13, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1 }),
  p('blowout',        { fontFamily: 'Bebas Neue',       fontSize: 22, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('goggins',        { fontFamily: 'Bebas Neue',       fontSize: 18, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2,   animation: 'impact' }),
  p('rogaine',        { fontFamily: 'Montserrat',       fontSize: 14, bold: true,  textColor: '#000000', outlineColor: '#FFEB3B', outlineWidth: 0,   hasBackground: true, backgroundColor: '#FFEB3B', backgroundOpacity: 1, animation: 'impact' }),
  p('mosying',        { fontFamily: 'Nunito',           fontSize: 11, textColor: '#f5f0e8', outlineColor: '#292524', outlineWidth: 1,   animation: 'fade' }),
  p('buzz',           { fontFamily: 'Barlow Condensed', fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('frost',          { fontFamily: 'Raleway',          fontSize: 12, textColor: '#e0f2fe', outlineColor: '#0c4a6e', outlineWidth: 1.5, animation: 'fade' }),

  // ── Confident series (1–11) ───────────────────────────────────────────────
  p('confident 1',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 2',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 3',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#f97316', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 4',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#f472b6', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 5',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#60a5fa', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 6',    { fontFamily: 'Montserrat',       fontSize: 14, bold: true, letterCase: 'uppercase', textColor: '#4ade80', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 7',    { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('confident 8',    { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('confident 9',    { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#f97316', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('confident 10',   { fontFamily: 'Oswald',           fontSize: 15, bold: true, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('confident 11',   { fontFamily: 'Oswald',           fontSize: 15, bold: true, letterCase: 'uppercase', textColor: '#facc15', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),

  // ── Friendly series (1–6) ─────────────────────────────────────────────────
  p('friendly 1',     { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#FFFFFF', outlineColor: '#1c1917', outlineWidth: 2,   animation: 'word-pop' }),
  p('friendly 2',     { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#fbbf24', outlineColor: '#1c1917', outlineWidth: 2,   animation: 'word-pop' }),
  p('friendly 3',     { fontFamily: 'Poppins',          fontSize: 12, textColor: '#FFFFFF', outlineColor: '#1c1917', outlineWidth: 2,   animation: 'word-pop' }),
  p('friendly 4',     { fontFamily: 'Poppins',          fontSize: 12, textColor: '#86efac', outlineColor: '#14532d', outlineWidth: 2,   animation: 'word-pop' }),
  p('friendly 5',     { fontFamily: 'Raleway',          fontSize: 12, textColor: '#FFFFFF', outlineColor: '#1c1917', outlineWidth: 1.5, animation: 'fade' }),
  p('friendly 6',     { fontFamily: 'Raleway',          fontSize: 12, textColor: '#fca5a5', outlineColor: '#7f1d1d', outlineWidth: 1.5, animation: 'fade' }),

  // ── Italic series (1–6) ───────────────────────────────────────────────────
  p('italic 1',       { fontFamily: 'Raleway',          fontSize: 13, italic: true, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2,   animation: 'fade' }),
  p('italic 2',       { fontFamily: 'Raleway',          fontSize: 13, italic: true, textColor: '#fbbf24', outlineColor: '#000000', outlineWidth: 2,   animation: 'fade' }),
  p('italic 3',       { fontFamily: 'Montserrat',       fontSize: 13, italic: true, bold: true, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2, animation: 'word-pop' }),
  p('italic 4',       { fontFamily: 'Poppins',          fontSize: 12, italic: true, textColor: '#f9a8d4', outlineColor: '#000000', outlineWidth: 1.5, animation: 'fade' }),
  p('italic 5',       { fontFamily: 'Playfair Display', fontSize: 13, italic: true, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('italic 6',       { fontFamily: 'Merriweather',     fontSize: 12, italic: true, textColor: '#fef9ee', outlineColor: '#292524', outlineWidth: 1 }),

  // ── Serif series (1, 3, 2, 4, 5 — original order) ────────────────────────
  p('serif 1',        { fontFamily: 'Playfair Display', fontSize: 13, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('serif 3',        { fontFamily: 'Playfair Display', fontSize: 13, bold: true,  textColor: '#fbbf24', outlineColor: '#1c1917', outlineWidth: 1 }),
  p('serif 2',        { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('serif 4',        { fontFamily: 'Merriweather',     fontSize: 11, italic: true, textColor: '#fde68a', outlineColor: '#1c1917', outlineWidth: 1 }),
  p('serif 5',        { fontFamily: 'Playfair Display', fontSize: 13, italic: true, bold: true, textColor: '#f9a8d4', outlineColor: '#1c1917', outlineWidth: 1 }),

  // ── Grand series (1–6) ────────────────────────────────────────────────────
  p('grand 1',        { fontFamily: 'Bebas Neue',       fontSize: 20, letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('grand 2',        { fontFamily: 'Bebas Neue',       fontSize: 20, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 3,   animation: 'impact' }),
  p('grand 3',        { fontFamily: 'Oswald',           fontSize: 18, bold: true,  letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('grand 4',        { fontFamily: 'Barlow Condensed', fontSize: 18, bold: true,  letterCase: 'uppercase', textColor: '#f97316', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('grand 5',        { fontFamily: 'Montserrat',       fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),
  p('grand 6',        { fontFamily: 'Montserrat',       fontSize: 16, bold: true,  letterCase: 'uppercase', textColor: '#60a5fa', outlineColor: '#000000', outlineWidth: 2.5, animation: 'impact' }),

  // ── Cute series (1–7) ─────────────────────────────────────────────────────
  p('cute 1',         { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#f9a8d4', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('cute 2',         { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#fbbf24', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('cute 3',         { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#f472b6', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('cute 4',         { fontFamily: 'Nunito',           fontSize: 13, bold: true,  textColor: '#a78bfa', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('cute 5',         { fontFamily: 'Caveat',           fontSize: 15, textColor: '#f472b6', outlineColor: '#FFFFFF', outlineWidth: 1.5, animation: 'word-pop' }),
  p('cute 6',         { fontFamily: 'Caveat',           fontSize: 15, textColor: '#34d399', outlineColor: '#FFFFFF', outlineWidth: 1.5, animation: 'word-pop' }),
  p('cute 7',         { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#f9a8d4', outlineColor: '#FFFFFF', outlineWidth: 1.5, animation: 'fade' }),

  // ── Final named styles ────────────────────────────────────────────────────
  p('gothic diva',    { fontFamily: 'Playfair Display', fontSize: 13, bold: true,  textColor: '#be123c', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'fade' }),
  p('citrus',         { fontFamily: 'Poppins',          fontSize: 13, bold: true,  textColor: '#fb923c', outlineColor: '#FFFFFF', outlineWidth: 2,   animation: 'word-pop' }),
  p('formik',         { fontFamily: 'Inter',            fontSize: 11, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1 }),
  p('lisa',           { fontFamily: 'Dancing Script',   fontSize: 14, italic: true, textColor: '#fda4af', outlineColor: '#FFFFFF', outlineWidth: 1,   animation: 'fade' }),
  p('promo',          { fontFamily: 'Bebas Neue',       fontSize: 16, letterCase: 'uppercase', textColor: '#FFEB3B', outlineColor: '#000000', outlineWidth: 0,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.85, animation: 'impact' }),
  p('sorbet',         { fontFamily: 'Nunito',           fontSize: 12, textColor: '#fb7185', outlineColor: '#FFFFFF', outlineWidth: 2,   hasBackground: true, backgroundColor: '#fff1f2', backgroundOpacity: 0.75, animation: 'fade' }),
  p('clean',          { fontFamily: 'Roboto',           fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('night',          { fontFamily: 'Inter',            fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 0,   hasBackground: true, backgroundColor: '#000000', backgroundOpacity: 0.8, animation: 'fade' }),
  p('blush bloom',    { fontFamily: 'Dancing Script',   fontSize: 14, textColor: '#f43f5e', outlineColor: '#FFFFFF', outlineWidth: 1.5, hasBackground: true, backgroundColor: '#fff1f2', backgroundOpacity: 0.7, animation: 'word-pop' }),
  p('readline',       { fontFamily: 'Source Sans 3',    fontSize: 12, textColor: '#FFFFFF', outlineColor: '#000000', outlineWidth: 1.5 }),
  p('serif patel',    { fontFamily: 'Merriweather',     fontSize: 11, textColor: '#292524', outlineColor: '#fef9ee', outlineWidth: 0,   hasBackground: true, backgroundColor: '#fef9ee', backgroundOpacity: 0.9 }),
  p('bunny',          { fontFamily: 'Pacifico',         fontSize: 13, textColor: '#f9a8d4', outlineColor: '#FFFFFF', outlineWidth: 2.5, animation: 'word-pop' }),
  p('glow marker',    { fontFamily: 'Caveat',           fontSize: 14, textColor: '#FFFFFF', outlineColor: '#22d3ee', outlineWidth: 3,   highlightColor: '#22d3ee', animation: 'karaoke' }),
];
